import pygame
from pygame.locals import *

pygame.init()

WHITE = (255,255,255)
BLACK = (0,0,0)
RED   = (255,0,0)
GREEN = (0,255,0)
BLUE  = (0,0,255)

FPS = 60
SCREEN_SIZE = [300,500]
FONT = pygame.font.SysFont('Times New Roman', 15)

GAMESTATE_MAINMENU = 1
GAMESTATE_SPACE = 2

SPACESTATE_NORMAL = 1
SPACESTATE_ASTERIODS = 2
SPAECSTATE_BATTLE = 3
SPACESTATE_BOSS = 4

WORLD_SIZE = pygame.math.Vector2(300, 500)
WORLD_POS = pygame.math.Vector2(5,0)
WORLD_BACKGROUND = WHITE

DUST_LAYER = 5
SPACESHIP_LAYER = 4
STONE_LAYER = 3
SHOT_LAYER = 2
EFFECT_LAYER = 1

PLAYER_SPACESHIP_SPEED = 2.5

CHANCE_NEW_STONE = 0.1
MAX_STONE_LEVEL = 3

BLUE_DUST_VALUE = 2
BLUE_DUST_FOLLOW_RADIUS = 400
BLUE_DUST_SPEED = 6
BLUE_DUST_MAX_TURN_ANGLE = 1
GREEN_DUST_VALUE = 5
GREEN_DUST_FOLLOW_RADIUS = 70
GREEN_DUST_SPEED = 2
CHANCE_GREEN_DUST = { 1 : 0.01 , 
                      2 : 0.1  , 
                      3 : 0.25  }
GREEN_DUST_ABS_V = 1
GREEN_DUST_MAX_ACCELERATION = 0.5

# Images
IMAGE_PATH = 'images/'

PLAYER_SPACESHIP_IMAGE = 'spaceship.png'
SHIELD_IMAGE = 'shield.png'
BLUE_DUST_IMAGE = 'blue_dust.png'
GREEN_DUST_IMAGE = 'green_dust.png'
EXPLOSION_IMAGE = 'explosion.png'

# Sounds
SOUND_PATH = 'sounds/'

COLLECT_SOUND = 'pop.wav'
COLLECT_VOLUME = 0.3
LASER_CANNON_SOUND = 'EnergyCannon.wav'
LASER_CANNON_VOLUME = 0.3
EXPLOSION_SOUND = 'explosion.wav'
EXPLOSION_VOLUME = 0.1

BACKGROUNDMUSIC = 'Faunts - M4 (Part II).mp3'
BACKGROUNDMUSIC_VOLUME = 1.0

# Controls

KEY_QUIT_GAME = K_q

KEY_MOVE_LEFT  = K_a
KEY_MOVE_RIGHT = K_d
KEY_SHOOT      = K_w

JOYBUTTON_QUIT_GAME = 0

JOYBUTTON_MOVE_LEFT  = 4
JOYBUTTON_MOVE_RIGHT = 6
JOYBUTTON_SHOOT      = 2
